name: GodlyzPlugin
version: '${project.version}'
main: com.sorkopiko.godlyzbox.GodlyzPlugin
api-version: '1.20'
authors: [SorkoPiko]
description: Plugin for Godlyzbox
website: sorkopiko.com

softdepend:
  - PlaceholderAPI
  - Vulcan
  - LuckPerms

commands:
  verify:
    description: Verify your account with your Discord account
    usage: "Usage: /verify <code>"
    permission: godlyzbox.verify
  warn:
    description: Warn a player
    usage: "Usage: /warn <player> <reason>"
    permission: godlyzbox.warn
  unwarn:
    description: Unwarn a player
    usage: "Usage: /unwarn <player> <reason>"
    permission: godlyzbox.warn
  warns:
    description: Check your warns
    usage: "Usage: /warns"
    permission: godlyzbox.warns
  checkwarns:
    description: Check player's warns
    usage: "Usage: /checkwarns <player>"
    permission: godlyzbox.checkwarns
permissions:
  godlyzbox.verify:
    description: Verify your account with your Discord account
    default: true
  godlyzbox.warn:
    description: Warn a player
    default: false
  godlyzbox.warns:
    description: Check your warns
    default: true
  godlyzbox.checkwarns:
    description: Check player's warns
    default: false